# File generated by cwl2click v{{ version }}
# timestamp: {{ timestamp }}

__all__ = []

{% for clt in command_line_tools %}from {{module_name}}.{{clt.id | to_snake_case}}_impl import execute as {{clt.id | to_snake_case}}_command
{% endfor %}
from pathlib import Path

import click

{% set groups=[] %}

{% for clt in command_line_tools %}
{% set base_command=clt | get_base_command | to_snake_case %}
{% set command_name=(clt | get_command_name) if bundle else none %}

{% if not base_command in groups %}# {{ groups.append(base_command) }}
__all__.append("{{base_command}}")
# NOTE
# Do not forget to add the section below in your `pyproject.toml` file
#  
# [project.scripts]
{% if bundle %}# {{command_name}} = "{{module_name}}.{{clt.id | to_snake_case}}:{{base_command}}"
{% else %}# {{clt.id}} = "{{module_name}}.cli:{{base_command}}"
{% endif %}
{% if command_name %}@click.group()
def {{base_command}}() -> None:
    pass
{% else %}
{{base_command}} = click.Command(
    name="{{base_command}}",
    callback={{clt.id | to_snake_case}}_command,
    help={{clt.doc | to_triple_quoted_string}},
    short_help={{clt.label | to_triple_quoted_string}},
    params=[
{% for input in clt.inputs %}            click.Option(
            ["{% if input.inputBinding.prefix %}{{input.inputBinding.prefix}}{% else %}--{{input.id}}{% endif %}"],
            "{{input.id | to_snake_case}}",
            type=click.{{input.type_ | to_click_type}},
            multiple={{input.type_ | is_multiple}},
            required={{input.type_ | is_required}},
            is_flag={{input.type_ | is_flag}},{% if input.doc %}
            help={{input.doc | to_triple_quoted_string}},{% endif %}
        ),
{% endfor %}    ]
){% endif %}{% endif %}

{% if command_name %}
{{base_command}}.add_command(
    click.Command(
        name="{{command_name}}",
        callback={{clt.id | to_snake_case}}_command,
        help={{clt.doc | to_triple_quoted_string}},
        short_help={{clt.label | to_triple_quoted_string}},
        params=[
{% for input in clt.inputs %}            click.Option(
                ["{% if input.inputBinding.prefix %}{{input.inputBinding.prefix}}{% else %}--{{input.id}}{% endif %}"],
                "{{input.id | to_snake_case}}",
                type=click.{{input.type_ | to_click_type}},
                multiple={{input.type_ | is_multiple}},
                required={{input.type_ | is_required}},
                is_flag={{input.type_ | is_flag}},{% if input.doc %}
                help={{input.doc | to_triple_quoted_string}},{% endif %}
            ),
{% endfor %}        ]
    )
)
{% endif %}
{% endfor %}
